version: '1.0'
stages:
  - tests
  - publish

steps:
  BuildImage:
    title: Build Image
    type: build
    image_name: cf-plugin-codeclimate
    tag: ${{CF_SHORT_REVISION}}

  Tests:
    type: parallel
    stage: tests
    fail_fast: false
    steps:
      TestMissingReporterId:
        title: 'Testing Missing CC_TEST_REPORTER_ID'
        image: ${{BuildImage}}
        commands:
          - report env --debug
      TestSimpleCommand:
        title: 'Testing Simple Env Command'
        image: ${{BuildImage}}
        environment:
          - CC_TEST_REPORTER_ID=123abc
        commands:
          - report env --debug
      TestMultipleCommands:
        title: 'Testing Before Build Command'
        image: ${{BuildImage}}
        environment:
          - CC_TEST_REPORTER_ID=123abc
        commands:
          - report env --debug
          - report before-build --debug

  VerifyTestResults:
    title: 'Verify Tests Results'
    stage: tests
    image: alpine:latest
    commands:
      - echo "Unit tests failed"
      - exit 1
    when:
      condition:
        any:
          TestMissingReporterId: steps.TestMissingReporterId.result != 'failure'
          TestSimpleRun: steps.TestSimpleRun.result != 'success'
          TestMultipleCommands: steps.TestMultipleCommands.result != 'success'

  Push:
    type: parallel
    stage: publish
    steps:
      PushMasterImage:
        title: Push Latest Image
        type: push
        candidate: ${{BuildImage}}
        image_name: maticinsurance/cf-plugin-codeclimate
        registry: dockerhub
        tags:
          - latest
        when:
          branch:
            only:
              - master

      PushReleaseImage:
        title: Push Release Image
        type: push
        candidate: ${{BuildImage}}
        image_name: maticinsurance/cf-plugin-codeclimate
        registry: dockerhub
        tags:
          - ${{CF_RELEASE_TAG}}
        when:
          condition:
            all:
              hasReleaseTag: 'match("${{CF_RELEASE_TAG}}", "^\d+\.\d+\.\d+$", true) == true'
